name: TerraformAzureDeploy
on:
  push:
    branches: 
    - main
env:
  ARM_CLIENT_ID: ${{ secrets.client_id }}
  ARM_CLIENT_SECRET: ${{ secrets.client_secret }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.subscription_id }}
  ARM_TENANT_ID: ${{ secrets.tenant_id }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check    
      
      - name: Terraform Plan
        run: terraform plan